### ISSUE TITLE
Integrating captcha to Symfony 4 login form

### ISSUE THREAD

**Issue by nuryagdym** [karser/KarserRecaptcha3Bundle#24]
Hi,

Can anybody share the way to integrate captcha to login form?
I did not find any example of using form builder for login form in Symfony 4

**Comment by karser** [comment]
I never did that with login but this use case is legit.
According to [the docs](https://symfony.com/doc/4.4/security/form_login_setup.html), the login form doesn't use the symfony/form component which this bundle provides integration for. If I needed to implement this task, I'd put [this](https://github.com/karser/KarserRecaptcha3Bundle#how-to-integrate-re-captcha-in-api-method) javascript on frontend
![image](https://user-images.githubusercontent.com/1675033/88192213-f21c3a00-cc44-11ea-8578-c014bf3c70db.png)
It makes sense to create twig exported function which renders this javascript.

And then I'd check the captcha value on backend in LoginFormAuthenticator in getUser method, along with csrf_token validation:
![image](https://user-images.githubusercontent.com/1675033/88192469-360f3f00-cc45-11ea-9521-7421708b5d8c.png)
In order to do that, I'd use [Recaptcha3Validator](https://github.com/karser/KarserRecaptcha3Bundle/blob/master/Validator/Constraints/Recaptcha3Validator.php) to validate the raw token, see [the docs](https://symfony.com/doc/4.4/validation/raw_values.html)

**Comment by nuryagdym** [comment]
Thanks @karser 
I integrated captcha validation by implementing custom authentication subscriber.
Here is the [gist code](https://gist.github.com/nuryagdym/ae946b8e696eb6c1a09c510b4ad66c35)

**Comment by karser** [comment]
I didn't know you use Symfony forms though. Thanks for the example, I'll add to the docs when I get to it.
